# Generated by Django 5.2.2 on 2025-06-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreExtractedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('location_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='api_preextr_name_95fc2c_idx'), models.Index(fields=['location_type'], name='api_preextr_locatio_064f8d_idx')],
            },
        ),
    ]
